# Generated by Django 5.1.2 on 2024-12-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapi', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
